---
- name: Provision Ec2 instance & install XX
  hosts: localhost
  gather_facts: false  #no
  roles:
    - ecr_setup

- name: Configuration of Ec2 instances
  hosts: launched_ec2_instances
  gather_facts: true #yes
  become: true  #yes
  roles: 
    - common 
    - docker

- name: Configuration of Monitoring Servers
  hosts: monitoring_ec2_instances
  gather_facts: true #yes
  become: true  #yes
  roles: 
    - monitoring
    